delivery-price
Oleksandr-Mokryi/Education pull request #1
Opened 2021-04-11 12:44 UTC by Oleksandr-Mokryi

Created feature to calculate order prices

2021-04-12 09:30 UTC, serhii-shkodenko requested changes
Поправь эти замечания, пожалуйста, попозже еще раз гляну.

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/DataCkecker.cs
> +                foreach(var i in num)
Да, чтобы узнать количество элементов в коллекции, другого алгоритма, как перебрать все элементы в массиве, нет. Однако для этого, есть более оптимальные пути, например:
           
```
            int count = 0;
            using (IEnumerator<TSource> e = source.GetEnumerator())
            {
                checked
                {
                    while (e.MoveNext())
                    {
                        count++;
                    }
                }
            }
```
Однако, в .NET уже есть для этого встроенные инструменты. Воспользуйтесь `Enumerable.Count()`, код из которого я привел выше.

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/DataCkecker.cs
> +        public bool Check_Equality(params IEnumerable[] coll)
Имена методов в С# не должны иметь знаков подчеркивания. Они должны называться в соответствии с PascalCase. С конвенцией можно ознакомиться [здесь](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/HomeWork.cs
> +namespace Delivery_price
Неймспейсы не должны содержать знаков подчеривания. На это прямо указывает [конвенция](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/HomeWork.cs
> +            }
Было бы логичным этот код разместить после объявления fullPrice. В случае невалидности данных, возвращаете ее.

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/HomeWork.cs
> +            fullPrice = order.Main_Screen();
Здесь тоже нужно поправить имя метода в соответствии с [конвенцями](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/HomeWork.cs
> +            // Your solution supposed to be here.
Этоь комментарий был оставлен для вас, поэтому после написания кода его можно с чистой совестью удалить.

2021-04-12 09:30 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/HomeWork.cs
> +            DataCkecker checker = new DataCkecker();
В C# широко используется неявное опеределение типа с помощью `var`. Лучше придерживаться этой [конвенции](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#implicitly-typed-local-variables).

2021-04-13 20:47 UTC, serhii-shkodenko requested changes

2021-04-13 20:47 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/DataCkecker.cs
> +        public bool CheckEquality(IEnumerable<decimal> sources1, params IEnumerable<object>[] sources2)
Чтобы провалидировать количество элементов в коллекции, достаточно было просто вызвать Count() на коллекции.

2021-04-13 20:47 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/HomeWork.cs
> +            fullPrice = order.MainScreen();
В С# в именах методов должны быть глаголы. Здесь можно ознакоиться с [соответствующей конвенцией](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members).

2021-04-13 20:47 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +                "USD" => 1.0m * price,
Здесь можно ничего не умножать, а просто вернуть цену без обработки.

2021-04-13 20:47 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +                while (clientsNum.MoveNext())
Попытайся подсчитать все с помощью лишь одного цикла.

2021-04-15 18:56 UTC, serhii-shkodenko requested changes

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const decimal addPay = 10.0m;
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const string streetWithAddPay = "Wayne Street";
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const string streetWithSubPay = "North Heather Street";
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const decimal subPay = 5.36m;
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const string nameUsd = "USD";
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const string nameEur = "EUR";
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const decimal exchRateEurToUsd = 1.19m;
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const decimal discountInfants = 0.5m;
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const decimal discountChildren = 0.75m;
Имена констант в С# принято называть в `PascalCase`.

2021-04-15 18:56 UTC, serhii-shkodenko commented on Delivery_price/Delivery_price/OrderBuilder.cs
> +        private const decimal discountSameStreet = 0.85m;
Имена констант в С# принято называть в `PascalCase`.

2021-04-16 12:26 UTC, serhii-shkodenko approved these changes
Александр, решение для получения предыдущего и следующего адреса является очень неоптимальным. Для того чтобы не выходить за границы массива, ты обрамил этот код в блок try...catch. 

Однако, эта конструкция для этого не предназначена, она служит для отлавливания возможных исключительных ситуаций. Здесь же бизнес логика предусматривает, что такой случай выхода за пределы массива будет происходить регулярно, при обработке каждого заказа. Здесь стоило бы выбрать другое решение. На продакшин такой код может попасть только по недосмотру. 

Ты получаешь апрув, но учти, пожалуйста, на будущее это замечание 🙂.  

Можно мержить.

2021-04-16 16:32 UTC, Oleksandr-Mokryi reviewed
> Александр, решение для получения предыдущего и следующего адреса является очень неоптимальным. Для того чтобы не выходить за границы массива, ты обрамил этот код в блок try...catch.
> 
> Однако, эта конструкция для этого не предназначена, она служит для отлавливания возможных исключительных ситуаций. Здесь же бизнес логика предусматривает, что такой случай выхода за пределы массива будет происходить регулярно, при обработке каждого заказа. Здесь стоило бы выбрать другое решение. На продакшин такой код может попасть только по недосмотру.
> 
> Ты получаешь апрув, но учти, пожалуйста, на будущее это замечание 🙂.
> 
> Можно мержить.

Спасибо. Хотел избавить код от лишних переменных и сделать компактнее. Учту в будущем.

2021-04-16 16:32 UTC, merged